### ISSUE TITLE
Multiple instances configuration?

### ISSUE THREAD

**Issue by eloo** [chatpal/chatpal-search-standalone#1]
Hello,
i've tested the chatpal-search together with rocketchat and noticed that when i'm trying to run two instances of chatpal behind a loadbalancer (kubernetes setup) that some search queries will return an emtpy result but some of them are returning a valid result (keyword found).
So i guess we need to configure the chatpal-search somehow?
I've found for solr a zookeeper argument, maybe that could be a solution?

Do you have any hints how a multiinstance chatpal-search setup could look like?
Thanks

**Comment by tkurz** [comment]
Hi @eloo
Currently the standalone ist only single instance, so loadbalancing will not work, as you have 2 indioendent instances. This could be solved using solr cloud with 2 or more servers and the configuration you can find in the repo. We will come back with a more detailed instruction!

**Comment by ja-fra** [comment]
Hi @eloo,

I've added a basic documentation on how to run chatpal-search-standalone in cloud mode based on Docker. 
I hope you can transfer this into a kubernetes setup - if you have any further questions please don't hesitate to ask.

**Comment by eloo** [comment]
pretty cool.. with test it asap ;)

**Comment by mrsimpson** [comment]
@eloo Did you get the SolrCloud-K8S-setup up and running? We're looking into this as well. And it would be very useful, to find a no-memory-leak-setup for Chatpal on Solr in K8S - be it SolrCloud or a Master-Slave-Setup!

**Comment by eloo** [comment]
@mrsimpson sorry but no.. didn't have time for that atm

**Comment by mrsimpson** [comment]
@eloo Do you have a setup with a running Solr-cloud already onto which you want to deploy Chatpal to or are you just looking for a failsafe way of setting up Chatpal on a k8s-cluster?

**Comment by eloo** [comment]
@mrsimpson i'm trying to create a HA setup for RocketChat together with ChatPal, so at least a i need two instances of ChatPal on the k8s-cluster yes.
