### ISSUE TITLE
Set df for the /chatpal/search ResponseHandler

### ISSUE THREAD

**Issue by westei** [chatpal/chatpal-search-standalone#4]
With [chatpal-search-solr-ext #7](https://github.com/chatpal/chatpal-search-solr-ext/issues/7) the `lucene` (default) query parser will be used in cases where the new `query` parameter is used.

To correctly parse queries without a defined field the configuration of the `/chatpal/search` ResponseHandler should be extended to define reasonable `df` values

**Comment by ja-fra** [comment]
Fixed in e89da04
