### ISSUE TITLE
/solr/chatpal not found - add basic setup instructions

### ISSUE THREAD

**Issue by felixkosmalla** [chatpal/chatpal-search-standalone#6]
I started the docker container as per instructions, but /solr/chatpal returns 'not found'. Are there any more steps for configuration?

Thanks a lot!

**Comment by ja-fra** [comment]
`http://YOUR-DOCKER-IP:8983/solr/chatpal` is the base-Url for the API  the [chatpal plugin](https://chatpal.io/) is working on.

After setting up the docker, configure the above URL in the administration screen of your rocket.chat-instance. The search-configuration is found under `Administration/Search`.

To get more technical insight you can navigate to `http://YOUR-DOCKER-IP:8983/solr` where the [Solr Admin UI](https://lucene.apache.org/solr/guide/7_2/overview-of-the-solr-admin-ui.html) is located.

**Comment by felixkosmalla** [comment]
/solr is aceessible, however /solr/chatpal is not. Did I do something wrong?

**Comment by ja-fra** [comment]
As I said: `/solr/chatpal` is the **base-path**.

If your're interested, the actual endpoints used can be looked up in the `solrconfig.xml`:
E.g. the healthcheck-endpoint is available at `/solr/chatpal/chatpal/ping`:
https://github.com/chatpal/chatpal-search-standalone/blob/e89da04a8db7b2a5b55c8be2736dcdde3b1dc103/solr-conf/chatpal/conf/solrconfig.xml#L441-L448

But to clarify: After starting the docker-image, there's **nothing more to do** in chatpal-search-standalone. Everything else is configured in your rocket.chat-instance.

**Comment by felixkosmalla** [comment]
Allright, thanks, my bad. I was misslead by the Rocket.Chat URL field.
`localhost:8983/solr/chatpal/chatpal/ping ` return something now.

However, when entering `http://localhost:8983/solr/chatpal/chatpal` in the config area of Rocket.Chat and restarting the Rocket.Chat server, and trying to search for something, I get `Current Search Provider is not active`.

Sorry for hijacking this issue as support thread...

**Comment by ja-fra** [comment]
Sorry for the long response-time:

You need to enter `http://localhost:8983/solr/chatpal` in the config area of Rocket.Chat - the plugin will then append the correct `/chatpal/ping|search|...` endpoint internally.
